---
- name: Install Docker-WordPress, Docker-MySQL and NGINX
  hosts: all
  remote_user: root
  roles:
    - docker
    - wordpress
    - nginx
    - ssl
  vars_files:
    - defaults/main.yml
  vars_prompt:
    - name: wp_db_psw
      prompt: "WordPress DB password: "
      private: yes
      default: "root"
      confirm: yes
    
    - name: email
      prompt: "User e-mail: "
      private: no
      default: "benjamin.tanone@gmail.com"
      confirm: yes
    
    