---
- name: Setup compose file structure
  file:
    path: "{{ compose_project_dir }}/{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: yes
    mode: 0755
  with_items:
  - wordpress
  - wp-db-data
  tags:
  - dir_ops

- name: deploy docker compose for WordPress
  template:
    src: docker-compose.yml.j2
    dest: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - deploy_compose

- name: Run docker-compose up
  command: docker-compose -f '{{ compose_project_dir }}/docker-compose.yml' up -d
  args:
    chdir: "{{ compose_project_dir }}"
  register: wpsuccess
